ADD

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -278,6 +278,12 @@ pip install psycopg2
 source "$BIN_DIR/steps/pip-install"
 mtime "pip.install.time" "${start}"
 
+echo "Verificando si Django está instalado..."
+if ! python -c "import django"; then
+  echo "Error: Django no está instalado"
+  exit 1
+fi
+
 # Support for NLTK corpora.
 (( start=$(nowms) ))
 sub_env "$BIN_DIR/steps/nltk"
